# -*- coding: utf-8 -*-
"""2702350075_Annisa_Luthfiah_Rahmah_INTEGRATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bsDFS8w27W3f0h1k9EgKc75RzEP49Fb
"""

import numpy as np

a = 0
b = np.pi
n = 11
h = (b -a) / (n -1)
x = np.linspace(a, b, n)
f = np.sin(x)

I_riemannL = h * sum(f[:n-1])
err_riemannL = 2 - I_riemannL

I_riemannR = h * sum(f[1::])
err_riemannR = 2 - I_riemannR

I_mid = h * sum(np.sin((x[:n-1] \
                       + x[1:])/2))
err_mid = 2 - I_mid

print(I_riemannL)
print(err_riemannL)

print(I_riemannR)
print(err_riemannR)

print(I_mid)
print(err_mid)

"""Trapezoid Rule"""

import numpy as np

a = 0
b = np.pi
n = 11
h = (b-a) / (n-1)
x = np.linspace(a, b, n)
f = np.sin(x)

I_trap = (h/2)*(f[0] + \
                 2 * sum(f[1:n-1]) + f[n-1])
err_trap = 2 - I_trap

print(I_trap)
print(err_trap)

"""Fungsi Trapz"""

import numpy as np
from scipy.integrate import trapz

a = 0
b = np.pi
n = 11
h = (b-a) / (n-1)
x = np.linspace(a, b, n)
f = np.sin(x)

I_trapz = trapz(f,x)
I_trap = (h/2) * (f[0] + 2 * sum(f[1:n-11] + f[n-1]))

print(I_trapz)
print(I_trap)

"""Fungsi Quad"""

from scipy.integrate import quad

I_quad, est_err_quad = \
          quad(np.sin, 0, np.pi)
print(I_quad)
err_quad = 2 - I_quad
print(est_err_quad, err_quad)

"""QUIZ"""

import numpy as np
import matplotlib.pyplot as plt

def trapezoidal_rule(f, a, b, n):
    h = (b - a) / n
    x = np.linspace(a, b, n + 1)
    y = f(x)
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral, x, y

# Define the function to integrate
def f(x):
    return np.sin(x)

# Define the integration bounds
a = 0
phi = np.pi / 2  # example value for phi, change as needed

# Number of panels
n1 = 8
n2 = 16

# Calculate the integrals
integral_8_panels, x_8, y_8 = trapezoidal_rule(f, a, phi, n1)
integral_16_panels, x_16, y_16 = trapezoidal_rule(f, a, phi, n2)

print(f"Integral with 8 panels: {integral_8_panels}")
print(f"Integral with 16 panels: {integral_16_panels}")

# Plotting the function and trapezoids for 8 panels
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.plot(x_8, f(x_8), 'b', label='sin(x)')
plt.fill_between(x_8, 0, y_8, color='skyblue', alpha=0.4, label='Trapezoids')
plt.title('Trapezoidal Rule with 8 Panels')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.legend()

# Plotting the function and trapezoids for 16 panels
plt.subplot(1, 2, 2)
plt.plot(x_16, f(x_16), 'b', label='sin(x)')
plt.fill_between(x_16, 0, y_16, color='skyblue', alpha=0.4, label='Trapezoids')
plt.title('Trapezoidal Rule with 16 Panels')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.legend()

plt.tight_layout()
plt.show()